# Generated by Django 3.2.4 on 2021-06-06 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0002_board_create_dt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='board',
            name='create_dt',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
