# Generated by Django 3.2.4 on 2021-06-06 22:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('board', '0003_alter_board_create_dt'),
    ]

    operations = [
        migrations.CreateModel(
            name='topic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('toptitle', models.CharField(max_length=100)),
                ('topdis', models.TextField(max_length=4000)),
                ('topdate_add', models.DateTimeField(auto_now_add=True)),
                ('topboard', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='board.board')),
                ('topcreated_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
