# Generated by Django 3.2.4 on 2021-06-06 22:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('board', '0004_topic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topic',
            name='topboard',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topic1', to='board.board'),
        ),
        migrations.AlterField(
            model_name='topic',
            name='topcreated_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topic2', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(max_length=4000)),
                ('create_dt', models.DateTimeField(auto_now_add=True)),
                ('create_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topic4', to=settings.AUTH_USER_MODEL)),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topic3', to='board.topic')),
            ],
        ),
    ]
