# Generated by Django 3.2.4 on 2021-06-08 16:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('board', '0005_auto_20210607_0134'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='filedlink',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='reboard', to='board.board'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='post',
            name='create_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topic', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='post',
            name='topic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topics', to='board.topic'),
        ),
        migrations.AlterField(
            model_name='topic',
            name='topboard',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topics', to='board.board'),
        ),
        migrations.AlterField(
            model_name='topic',
            name='topcreated_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topics', to=settings.AUTH_USER_MODEL),
        ),
    ]
