# Generated by Django 3.2.4 on 2021-06-10 05:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0007_auto_20210610_0758'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='board',
            name='topcreated_by',
        ),
    ]
