# Generated by Django 3.2.4 on 2021-06-10 05:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0011_board_topcreated_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='board',
            name='topcreated_by',
        ),
    ]
