# Generated by Django 3.2.4 on 2021-06-12 09:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0014_remove_board_topcreated_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topic',
            name='topboard',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Topic_Board', to='board.board'),
        ),
    ]
